### ISSUE TITLE
Required `ratar` updates

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/ratar#13]
Updates needed for this code base:

## December 2021

See PR #14 for details.

- [x] Update environment file as suggested by @t-kimber in #12 
- [x] Check if CLI is still running > now it is again.
- [x] Update README + installation + usage instructions (update tutorial!!!!)
- [x] Fill follow-up section below

### Methodology / encoding
- [ ] So far only full pocket encoding; we probably need subpocket encoding (overlapping patches)
- [ ] Define binding sites and their size #7
- [ ] Include non-standard amino acids #8
- [ ] Check units of 4th to 6th dimensions of reference points 
- [ ] Check units and scaling of moments - First three moments of distribution:
  - Same units: 2nd moment - standard deviation; 3rd moment: 3rd root of skewness
  - Scaling: none (should fingerprint/moments be normalised?) 
- [ ] We started to look into pdbqt files to be added as "physchem" properties to our fingerprint, take a look at [this notebook](https://github.com/volkamerlab/ratar/tree/master/docs/exploration/pdbqt) if still of interest
- [ ] We already started to benchmark the method against similar/dissimilar pocket pairs from FuzCav, ProSPECCTs, and TOUGH-M1 (see [README](https://github.com/volkamerlab/ratar/blob/master/scripts/README.md))
- [ ] Encoding workers fine for mol2 files; pdb files may not and need revision
- [ ] Since we probably have to move to NGLview anyways, PyMol functions have not been checked since 2019; probably they do not work anymore.

### Testing and CI

- [ ] Add unit tests for `similarity` module
- [ ] CI: Add back Windows + MacOS support, lint package, format+lint+test docs tutorials

### Code

- [ ] Check `similarity` module - refactoring needed?
- [ ] Address #FIXMEs and #TODOs in code (left-overs of major refactoring in PR #1); to be done after setting up unit tests
- [ ] Remove `pymol` dependency (not on `conda-forge`; currently installed from [`tpeulen`](https://anaconda.org/tpeulen/pymol-open-source))
- [ ] Remove `flatten-dict` dependency (only `pip`-installable)
- [ ] Add `from_path` class method to all `ratar.encoding` classes: Write class method `from_path`, analogous to `from_molecule`. Current problem: files can contain multiple molecules, thus `from_path` would return a list of molecule objects instead of a molecule object as in the case of `from_molecule`. 
- [ ] We set up a `logging.conf` file to fine-grain our logging. Include back into the package if of interest.

### Packaging

- [ ] Update `ratar` environment - enable `conda` packaging

**Comment by dominiquesydow** [comment]
Hi @AndreaVolkamer, just for visibility, this is a list of todos I put together before I left in Dec 2021. It is probably outdated already but some of the things might be relevant for your new student.
